export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS';
export const SESSION_CREATE_FAILURE = 'SESSION_CREATE_FAILURE';

export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAILURE = 'ACCOUNT_CREATE_FAILURE';

//**************MENU*****************//

export const MENU_LIST_FETCH_SUCCESS = 'MENU_LIST_FETCH_SUCCESS';
export const MENU_LIST_FETCH_FAILURE = 'MENU_LIST_FETCH_FAILURE';

export const MENU_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS';
export const MENU_FETCH_FAILURE = 'MENU_FETCH_FAILURE';
export const MENU_CREATE_SUCCESS = 'MENU_CREATE_SUCCESS';
export const MENU_CREATE_FAILURE = 'MENU_CREATE_FAILURE';
export const MENU_UPDATE_SUCCESS = 'MENU_UPDATE_SUCCESS';
export const MENU_UPDATE_FAILURE = 'MENU_UPDATE_FAILURE';
export const MENU_REMOVE_SUCCESS = 'MENU_REMOVE_SUCCESS';
export const MENU_REMOVE_FAILURE = 'MENU_REMOVE_FAILURE';

//**************PLACE*****************//
