//**************SESSION*****************//
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS';
export const SESSION_CREATE_FAILURE = 'SESSION_CREATE_FAILURE';
export const SESSION_REMOVE_SUCCESS = 'SESSION_REMOVE_SUCCESS';

//**************ACCOUNT*****************//
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAILURE = 'ACCOUNT_CREATE_FAILURE';
export const ACCOUNT_FETCH_SUCCESS = 'ACCOUNT_FETCH_SUCCESS';
export const ACCOUNT_FETCH_FAILURE = 'ACCOUNT_FETCH_FAILURE';

export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS';
export const ACCOUNT_UPDATE_FAILURE = 'ACCOUNT_UPDATE_FAILURE';

//**************PLACE*****************//
export const PLACE_CREATE_SUCCESS = 'PLACE_CREATE_SUCCESS';
export const PLACE_CREATE_FAILURE = 'PLACE_CREATE_FAILURE';
export const PLACE_FETCH_SUCCESS = 'PLACE_FETCH_SUCCESS';
export const PLACE_FETCH_FAILURE = 'PLACE_FETCH_FAILURE';
export const PLACE_UPDATE_SUCCESS = 'PLACE_UPDATE_SUCCESS';
export const PLACE_UPDATE_FAILURE = 'PLACE_UPDATE_FAILURE';

//**************TYPE PLACE*****************//
export const TYPEPLACE_LIST_SUCCESS = 'TYPEPLACE_LIST_SUCCESS';
export const TYPEPLACE_LIST_FAILURE = 'TYPEPLACE_LIST_FAILURE';

//**************MENU*****************//

export const MENU_LIST_FETCH_SUCCESS = 'MENU_LIST_FETCH_SUCCESS';
export const MENU_LIST_FETCH_FAILURE = 'MENU_LIST_FETCH_FAILURE';

export const MENU_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS';
export const MENU_FETCH_FAILURE = 'MENU_FETCH_FAILURE';
export const MENU_CREATE_SUCCESS = 'MENU_CREATE_SUCCESS';
export const MENU_CREATE_FAILURE = 'MENU_CREATE_FAILURE';
export const MENU_UPDATE_SUCCESS = 'MENU_UPDATE_SUCCESS';
export const MENU_UPDATE_FAILURE = 'MENU_UPDATE_FAILURE';
export const MENU_REMOVE_SUCCESS = 'MENU_REMOVE_SUCCESS';
export const MENU_REMOVE_FAILURE = 'MENU_REMOVE_FAILURE';

export const MENU_LIST_SUCCESS = 'MENU_LIST_SUCCESS';
export const MENU_LIST_FAILURE = 'MENU_LIST_FAILURE';

//**************DISH*****************//
export const TYPE_DISH_LIST_SUCCESS = 'TYPE_DISH_LIST_SUCCESS';
export const TYPE_DISH_LIST_FAILURE = 'TYPE_DISH_LIST_FAILURE';

export const DISH_CREATE_SUCCESS = 'DISH_CREATE_SUCCESS';
export const DISH_CREATE_FAILURE = 'DISH_CREATE_FAILURE';

export const DISH_LIST_SUCCESS = 'DISH_LIST_SUCCESS';
export const DISH_LIST_FAILURE = 'DISH_LIST_FAILURE';

export const DISH_REMOVE_SUCCESS = 'DISH_REMOVE_SUCCESS';
export const DISH_REMOVE_FAILURE = 'DISH_REMOVE_FAILURE';

//**************MENU----DISH*****************//
export const MENU_DISH_SUCCESS = 'MENU_DISH_SUCCESS';
export const MENU_DISH_FAILURE = 'MENU_DISH_FAILURE';

export const MENU_DISH_FETCH_SUCCESS = 'MENU_DISH_FETCH_SUCCESS';
export const MENU_DISH_FETCH_FAILURE = 'MENU_DISH_FETCH_FAILURE';

export const MENU_DISH_REMOVE_SUCCESS = 'MENU_DISH_REMOVE_SUCCESS';
export const MENU_DISH_REMOVE_FAILURE = 'MENU_DISH_REMOVE_FAILURE';

//**************PERSONAL*****************//
export const TYPE_PERSONAL_LIST_SUCCESS = 'TYPE_PERSONAL_LIST_SUCCESS';
export const TYPE_PERSONAL_LIST_FAILURE = 'TYPE_PERSONAL_LIST_FAILURE';

export const PERSONAL_CREATE_SUCCESS = 'PERSONAL_CREATE_SUCCESS';
export const PERSONAL_CREATE_FAILURE = 'PERSONAL_CREATE_FAILURE';

export const PERSONAL_LIST_SUCCESS = 'PERSONAL_LIST_SUCCESS';
export const PERSONAL_LIST_FAILURE = 'PERSONAL_LIST_FAILURE';

//**************ADRRESS*****************//

export const ADRRESS_CREATE_SUCCESS = 'ADRRESS_CREATE_SUCCESS';
export const ADRRESS_CREATE_FAILURE = 'ADRRESS_CREATE_FAILURE';

export const ADRRESS_LIST_SUCCESS = 'ADRRESS_LIST_SUCCESS';
export const ADRRESS_LIST_FAILURE = 'ADRRESS_LIST_FAILURE';

//**************ORDER*****************//

export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAILURE = 'ORDER_LIST_FAILURE';

export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAILURE = 'ORDER_FETCH_FAILURE';


//**************SOCKET*****************//

export const SOCKET_CONNECT =  'SOCKET_CONNECT';
export const SOCKET_DISCONNECT =  'SOCKET_DISCONNECT';